# SPDX-License-Identifier: AGPL-3.0-or-later

cmake_minimum_required(VERSION 3.25)

foreach(required IN ITEMS MORPHEUS_STEMLIB_ROOT MORPHEUS_STEMLIB_MANIFEST
                          MORPHEUS_STEMLIB_MANIFEST_VALIDATOR
                          MORPHEUS_STEMLIB_STAGER MORPHEUS_STEMLIB_BUILDER
                          MORPHEUS_STEMLIB_LEXICAL_BUILDER
                          MORPHEUS_STEMLIB_LEXICAL_MANIFEST
                          MORPHEUS_STEMLIB_LEXICAL_CORRECTIONS
                          MORPHEUS_STEMLIB_LANGUAGE MORPHEUS_STEMLIB_STAGE
                          MORPHEUS_BUILDEND MORPHEUS_BUILDDERIV
                          MORPHEUS_INDENDTABLES MORPHEUS_INDDERIVTABLES
                          MORPHEUS_STEMLIB_TOOLS_DIR
                          MORPHEUS_SOURCE_REVISION MORPHEUS_C_COMPILER
                          MORPHEUS_C_COMPILER_ID MORPHEUS_C_COMPILER_VERSION
                          MORPHEUS_SYSTEM_NAME MORPHEUS_SYSTEM_PROCESSOR
                          MORPHEUS_QUALIFICATION_PROFILE MORPHEUS_PYTHON
                          MORPHEUS_PERL)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()

if(NOT MORPHEUS_STEMLIB_LANGUAGE MATCHES "^(Greek|Latin)$")
  message(FATAL_ERROR "MORPHEUS_STEMLIB_LANGUAGE must be Greek or Latin")
endif()
if(EXISTS "${MORPHEUS_STEMLIB_STAGE}")
  message(FATAL_ERROR "stemlib production stage already exists")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}"
          -DMORPHEUS_STEMLIB_ROOT=${MORPHEUS_STEMLIB_ROOT}
          -DMORPHEUS_STEMLIB_MANIFEST=${MORPHEUS_STEMLIB_MANIFEST}
          -DMORPHEUS_STEMLIB_MANIFEST_VALIDATOR=${MORPHEUS_STEMLIB_MANIFEST_VALIDATOR}
          -DMORPHEUS_STEMLIB_STAGER=${MORPHEUS_STEMLIB_STAGER}
          -DMORPHEUS_STEMLIB_LANGUAGE=${MORPHEUS_STEMLIB_LANGUAGE}
          -DMORPHEUS_STEMLIB_STAGE=${MORPHEUS_STEMLIB_STAGE}
          -DMORPHEUS_BUILDEND=${MORPHEUS_BUILDEND}
          -DMORPHEUS_BUILDDERIV=${MORPHEUS_BUILDDERIV}
          -DMORPHEUS_INDENDTABLES=${MORPHEUS_INDENDTABLES}
          -DMORPHEUS_INDDERIVTABLES=${MORPHEUS_INDDERIVTABLES}
          -DMORPHEUS_SOURCE_REVISION=${MORPHEUS_SOURCE_REVISION}
          -DMORPHEUS_C_COMPILER=${MORPHEUS_C_COMPILER}
          -DMORPHEUS_C_COMPILER_ID=${MORPHEUS_C_COMPILER_ID}
          -DMORPHEUS_C_COMPILER_VERSION=${MORPHEUS_C_COMPILER_VERSION}
          -DMORPHEUS_SYSTEM_NAME=${MORPHEUS_SYSTEM_NAME}
          -DMORPHEUS_SYSTEM_PROCESSOR=${MORPHEUS_SYSTEM_PROCESSOR}
          -DMORPHEUS_QUALIFICATION_PROFILE=${MORPHEUS_QUALIFICATION_PROFILE}
          -DMORPHEUS_PRODUCTION_RECIPE=${CMAKE_CURRENT_LIST_FILE}
          -P "${MORPHEUS_STEMLIB_BUILDER}"
  RESULT_VARIABLE table_result
  OUTPUT_VARIABLE table_output
  ERROR_VARIABLE table_error
)
if(NOT table_result EQUAL 0)
  message(FATAL_ERROR "table production failed:\n${table_output}${table_error}")
endif()

execute_process(
  COMMAND "${MORPHEUS_PYTHON}" "${MORPHEUS_STEMLIB_LEXICAL_BUILDER}"
          --stage "${MORPHEUS_STEMLIB_STAGE}"
          --source "${MORPHEUS_STEMLIB_ROOT}"
          --manifest "${MORPHEUS_STEMLIB_LEXICAL_MANIFEST}"
          --corrections "${MORPHEUS_STEMLIB_LEXICAL_CORRECTIONS}"
          --language "${MORPHEUS_STEMLIB_LANGUAGE}"
          --tools "${MORPHEUS_STEMLIB_TOOLS_DIR}"
          --perl "${MORPHEUS_PERL}"
  RESULT_VARIABLE lexical_result
  OUTPUT_VARIABLE lexical_output
  ERROR_VARIABLE lexical_error
)
if(NOT lexical_result EQUAL 0)
  message(FATAL_ERROR "lexical production failed:\n${lexical_output}${lexical_error}")
endif()

set(receipt "${MORPHEUS_STEMLIB_STAGE}/MORPHEUS-STEMLIB-PRODUCTION-RECEIPT.json")
if(NOT EXISTS "${receipt}")
  message(FATAL_ERROR "stemlib production completed without a receipt")
endif()
