
/* gkstring.c */
gk_string *CreatGkString(int);
void FreeGkString(gk_string *);
gk_analysis *CreatGkAnal(int);
void FreeGkAnal(gk_analysis *);
int EnsureGkAnalStorage(gk_word *);
void ReleaseGkAnalStorage(gk_word *);
void DetachGkAnalStorage(gk_word *);
gk_word *CreatGkword(int);
void ClearGkstring(gk_string *);
void FreeGkword(gk_word *);
void CpGkAnal(gk_word *, gk_word *);
int CompGkString(const void *, const void *);
int CompGkForms(gk_word *, gk_word *);
int low_bit_of(int);
int CompByDictStr(const void *, const void *);
int RevCompByStr(gk_string *, gk_string *);
void PrntGkStrings(gk_string *, FILE *);
void PrntGkParadigm(gk_string *, FILE *);
void PrntGkStr(gk_string *, FILE *);
void PrntGkFlags(gk_string *, FILE *);
void PrntDomains(char *, FILE *);
void PrntMorphFlags(MorphFlags *, FILE *);
void PrntVerbInfo(word_form, FILE *);
void PrntParadigmInfo(word_form, FILE *);
int AddParadigmInfo(char *, size_t, word_form, const char *);
int AddPersNumInfo(char *, size_t, word_form, const char *);
void PrntPersNumInfo(word_form, FILE *);
void PrntAdjInfo(word_form, FILE *);
int AddAdjInfo(char *, size_t, word_form, const char *);
void PrntStemtype(Stemtype, FILE *);
void PrntDialect(Dialect, FILE *);
int AddDialect(Dialect, char *, size_t, const char *);
Dialect AndDialect(Dialect, Dialect);
int xInsertGstr(gk_string *, gk_string *, int,
                 int (*compare)(char *, char *), int);
int GetTableLine(char *, int, FILE *);
int eq_forminfo(word_form, word_form);
int SprintGkFlags(gk_string *, char *, size_t, const char *, int);
int DbaseFormat(gk_string *, char *, size_t, const char *, int);
